server:
  port: 5001
spring:
  datasource:
    url: jdbc:mysql://47.98.126.166:8802/panjilake?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: pjlakeqhvision
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  resources:
    static-locations: classpath:static/